# Generated by Django 3.2 on 2023-07-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230719_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
