# Generated by Django 3.2 on 2023-07-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20230724_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(default='кг', max_length=100),
        ),
    ]
