# Generated by Django 3.2 on 2023-10-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='recipes/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(db_index=False, max_length=200, unique=True, verbose_name='Уникальный слаг'),
        ),
    ]
