# Generated by Django 3.2 on 2023-08-09 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amountofingredients',
            options={'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Количество ингредиентов'},
        ),
        migrations.RemoveConstraint(
            model_name='amountofingredients',
            name='unique_ingredient_in_recipe',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
    ]
