# Generated by Django 3.2 on 2023-08-08 08:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountofingredients',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(1, message='Количество не может быть меньше 1 единицы!')], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='amountofingredients',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='recipes.ingredient', verbose_name='Список ингредиентов'),
        ),
        migrations.AlterField(
            model_name='amountofingredients',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='recipes.recipe', verbose_name='Рецепт'),
        ),
    ]
