# Generated by Django 3.2 on 2023-08-08 08:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20230808_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountofingredients',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Количество не может быть меньше 1 единицы!')], verbose_name='Количество'),
        ),
    ]
