# Generated by Django 3.2 on 2023-08-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_ingredients'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='amountofingredients',
            constraint=models.UniqueConstraint(fields=('ingredient', 'recipe'), name='unique_ingredient_in_recipe'),
        ),
    ]
