# Generated by Django 3.2 on 2023-08-08 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_amountofingredients_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amountofingredients',
            options={'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Количество ингредиентов'},
        ),
        migrations.RemoveConstraint(
            model_name='amountofingredients',
            name='unique_ingredient_in_recipe',
        ),
    ]
