# Generated by Django 3.2 on 2023-08-09 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_amountofingredients_unique_ingredient_in_recipe'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='amountofingredients',
            name='unique_ingredient_in_recipe',
        ),
    ]
