# Generated by Django 3.2 on 2023-08-08 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_amountofingredients_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountofingredients',
            name='recipe',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='recipes.recipe', verbose_name='Рецепт'),
        ),
    ]
