# Generated by Django 3.2 on 2023-08-16 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_recipe_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image',
        ),
    ]
