# Generated by Django 3.2 on 2023-08-18 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_remove_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountofingredients',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amounts', to='recipes.ingredient', verbose_name='Список ингредиентов'),
        ),
        migrations.AlterField(
            model_name='amountofingredients',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amounts_of_ingredients', to='recipes.recipe', verbose_name='Рецепт'),
        ),
    ]
