# Generated by Django 3.2 on 2023-08-08 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20230808_1613'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='amountofingredients',
            name='unique_ingredient_in_recipe',
        ),
    ]
