# Generated by Django 3.2 on 2023-08-08 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_remove_amountofingredients_unique_ingredient_in_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
    ]
